name: Build TACHY APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y openjdk-17-jdk unzip wget git zip \
          autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake \
          libffi-dev libssl-dev build-essential

      # ✅ Install Android SDK in Buildozer's real path
      - name: Install Android SDK for Buildozer
        run: |
          mkdir -p /home/runner/.buildozer/android/platform
          cd /home/runner/.buildozer/android/platform

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip
          unzip sdk.zip
          mv cmdline-tools android-sdk

          yes | android-sdk/bin/sdkmanager --licenses

          android-sdk/bin/sdkmanager \
            "platform-tools" \
            "platforms;android-33" \
            "build-tools;33.0.2"

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - uses: actions/upload-artifact@v4
        with:
          name: tachy-apk
          path: bin/*.apk
